### PR TITLE
Add fork me on github ribbon

### PR DESCRIPTION
**Pull request by ghoranyi**
What do you think @kbence, should we have this?

### CODE REVIEW

**Comment by kbence** [comment]
We can put it there, but I'd put it somewhere else in the DOM.

**Comment by ghoranyi** [comment]
right. Where would you put it?

**Comment by kbence** [comment]
In between `<body>` and `<header>`

**Comment by ghoranyi** [comment]
Like so?

**Review by kbence — APPROVED** [review]
Exactly 👍 !

**Pull request merged**
